const HOUR_SECONDS = 60 * 60;
const DAY_SECONDS = HOUR_SECONDS * 24;

const ACCESS_TOKEN_WINDOW_SECONDS = 60 * 15;
const REFRESH_TOKEN_WINDOW_SECONDS = DAY_SECONDS * 14;
const REFRESH_TOKEN_ENABLED_WINDOW_SECONDS = 90;

module.exports = {
  ACCESS_TOKEN_WINDOW_SECONDS,
  REFRESH_TOKEN_WINDOW_SECONDS,
  REFRESH_TOKEN_ENABLED_WINDOW_SECONDS,
};
