const HOUR_SECONDS = 60 * 60;
const DAY_SECONDS = HOUR_SECONDS * 24;

const MFA_ACCESS_TOKEN_WINDOW_SECONDS = 60 * 8;
const MFA_CUTOFF_TIMESTAMP = () => Date.now() - DAY_SECONDS * 2 * 1000;
const MFA_RESEND_ALLOW_AFTER_MS = 60 * 1000;

module.exports = {
  MFA_ACCESS_TOKEN_WINDOW_SECONDS,
  MFA_CUTOFF_TIMESTAMP,
  MFA_RESEND_ALLOW_AFTER_MS,
};
